package com.dce.business.entity.alipaymentOrder;

import java.util.ArrayList;
import java.util.List;
import java.math.BigDecimal;
import java.util.Date;

public class AlipaymentOrderExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	public AlipaymentOrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOrderidIsNull() {
			addCriterion("orderId is null");
			return (Criteria) this;
		}

		public Criteria andOrderidIsNotNull() {
			addCriterion("orderId is not null");
			return (Criteria) this;
		}

		public Criteria andOrderidEqualTo(Integer value) {
			addCriterion("orderId =", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidNotEqualTo(Integer value) {
			addCriterion("orderId <>", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidGreaterThan(Integer value) {
			addCriterion("orderId >", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidGreaterThanOrEqualTo(Integer value) {
			addCriterion("orderId >=", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidLessThan(Integer value) {
			addCriterion("orderId <", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidLessThanOrEqualTo(Integer value) {
			addCriterion("orderId <=", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidIn(List<Integer> values) {
			addCriterion("orderId in", values, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidNotIn(List<Integer> values) {
			addCriterion("orderId not in", values, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidBetween(Integer value1, Integer value2) {
			addCriterion("orderId between", value1, value2, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidNotBetween(Integer value1, Integer value2) {
			addCriterion("orderId not between", value1, value2, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrdercodeIsNull() {
			addCriterion("orderCode is null");
			return (Criteria) this;
		}

		public Criteria andOrdercodeIsNotNull() {
			addCriterion("orderCode is not null");
			return (Criteria) this;
		}

		public Criteria andOrdercodeEqualTo(String value) {
			addCriterion("orderCode =", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeNotEqualTo(String value) {
			addCriterion("orderCode <>", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeGreaterThan(String value) {
			addCriterion("orderCode >", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeGreaterThanOrEqualTo(String value) {
			addCriterion("orderCode >=", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeLessThan(String value) {
			addCriterion("orderCode <", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeLessThanOrEqualTo(String value) {
			addCriterion("orderCode <=", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeLike(String value) {
			addCriterion("orderCode like", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeNotLike(String value) {
			addCriterion("orderCode not like", value, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeIn(List<String> values) {
			addCriterion("orderCode in", values, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeNotIn(List<String> values) {
			addCriterion("orderCode not in", values, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeBetween(String value1, String value2) {
			addCriterion("orderCode between", value1, value2, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrdercodeNotBetween(String value1, String value2) {
			addCriterion("orderCode not between", value1, value2, "ordercode");
			return (Criteria) this;
		}

		public Criteria andOrderstatusIsNull() {
			addCriterion("orderStatus is null");
			return (Criteria) this;
		}

		public Criteria andOrderstatusIsNotNull() {
			addCriterion("orderStatus is not null");
			return (Criteria) this;
		}

		public Criteria andOrderstatusEqualTo(Integer value) {
			addCriterion("orderStatus =", value, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusNotEqualTo(Integer value) {
			addCriterion("orderStatus <>", value, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusGreaterThan(Integer value) {
			addCriterion("orderStatus >", value, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("orderStatus >=", value, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusLessThan(Integer value) {
			addCriterion("orderStatus <", value, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusLessThanOrEqualTo(Integer value) {
			addCriterion("orderStatus <=", value, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusIn(List<Integer> values) {
			addCriterion("orderStatus in", values, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusNotIn(List<Integer> values) {
			addCriterion("orderStatus not in", values, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusBetween(Integer value1, Integer value2) {
			addCriterion("orderStatus between", value1, value2, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andOrderstatusNotBetween(Integer value1, Integer value2) {
			addCriterion("orderStatus not between", value1, value2, "orderstatus");
			return (Criteria) this;
		}

		public Criteria andTotalamountIsNull() {
			addCriterion("totalAmount is null");
			return (Criteria) this;
		}

		public Criteria andTotalamountIsNotNull() {
			addCriterion("totalAmount is not null");
			return (Criteria) this;
		}

		public Criteria andTotalamountEqualTo(BigDecimal value) {
			addCriterion("totalAmount =", value, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountNotEqualTo(BigDecimal value) {
			addCriterion("totalAmount <>", value, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountGreaterThan(BigDecimal value) {
			addCriterion("totalAmount >", value, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("totalAmount >=", value, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountLessThan(BigDecimal value) {
			addCriterion("totalAmount <", value, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("totalAmount <=", value, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountIn(List<BigDecimal> values) {
			addCriterion("totalAmount in", values, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountNotIn(List<BigDecimal> values) {
			addCriterion("totalAmount not in", values, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("totalAmount between", value1, value2, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("totalAmount not between", value1, value2, "totalamount");
			return (Criteria) this;
		}

		public Criteria andReceptamountIsNull() {
			addCriterion("receptAmount is null");
			return (Criteria) this;
		}

		public Criteria andReceptamountIsNotNull() {
			addCriterion("receptAmount is not null");
			return (Criteria) this;
		}

		public Criteria andReceptamountEqualTo(BigDecimal value) {
			addCriterion("receptAmount =", value, "receptamount");
			return (Criteria) this;
		}

		public Criteria andReceptamountNotEqualTo(BigDecimal value) {
			addCriterion("receptAmount <>", value, "receptamount");
			return (Criteria) this;
		}

		public Criteria andReceptamountGreaterThan(BigDecimal value) {
			addCriterion("receptAmount >", value, "receptamount");
			return (Criteria) this;
		}

		public Criteria andReceptamountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("receptAmount >=", value, "receptamount");
			return (Criteria) this;
		}

		public Criteria andReceptamountLessThan(BigDecimal value) {
			addCriterion("receptAmount <", value, "receptamount");
			return (Criteria) this;
		}

		public Criteria andReceptamountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("receptAmount <=", value, "receptamount");
			return (Criteria) this;
		}

		public Criteria andReceptamountIn(List<BigDecimal> values) {
			addCriterion("receptAmount in", values, "receptamount");
			return (Criteria) this;
		}

		public Criteria andReceptamountNotIn(List<BigDecimal> values) {
			addCriterion("receptAmount not in", values, "receptamount");
			return (Criteria) this;
		}

		public Criteria andReceptamountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("receptAmount between", value1, value2, "receptamount");
			return (Criteria) this;
		}

		public Criteria andReceptamountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("receptAmount not between", value1, value2, "receptamount");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("createTime is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("createTime is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterion("createTime =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterion("createTime <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterion("createTime >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("createTime >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterion("createTime <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterion("createTime <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterion("createTime in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterion("createTime not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterion("createTime between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterion("createTime not between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNull() {
			addCriterion("updateTime is null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNotNull() {
			addCriterion("updateTime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeEqualTo(Date value) {
			addCriterion("updateTime =", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotEqualTo(Date value) {
			addCriterion("updateTime <>", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThan(Date value) {
			addCriterion("updateTime >", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("updateTime >=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThan(Date value) {
			addCriterion("updateTime <", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
			addCriterion("updateTime <=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIn(List<Date> values) {
			addCriterion("updateTime in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotIn(List<Date> values) {
			addCriterion("updateTime not in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeBetween(Date value1, Date value2) {
			addCriterion("updateTime between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
			addCriterion("updateTime not between", value1, value2, "updatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ct_alipay_trade
	 * @mbg.generated  Mon Aug 20 18:57:20 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ct_alipay_trade
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 20 09:29:33 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}