package com.dce.business.entity.message;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NoticeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public NoticeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeIsNull() {
            addCriterion("notice_type is null");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeIsNotNull() {
            addCriterion("notice_type is not null");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeEqualTo(Integer value) {
            addCriterion("notice_type =", value, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeNotEqualTo(Integer value) {
            addCriterion("notice_type <>", value, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeGreaterThan(Integer value) {
            addCriterion("notice_type >", value, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("notice_type >=", value, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeLessThan(Integer value) {
            addCriterion("notice_type <", value, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeLessThanOrEqualTo(Integer value) {
            addCriterion("notice_type <=", value, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeIn(List<Integer> values) {
            addCriterion("notice_type in", values, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeNotIn(List<Integer> values) {
            addCriterion("notice_type not in", values, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeBetween(Integer value1, Integer value2) {
            addCriterion("notice_type between", value1, value2, "noticeType");
            return (Criteria) this;
        }

        public Criteria andNoticeTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("notice_type not between", value1, value2, "noticeType");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andListImageIsNull() {
            addCriterion("list_image is null");
            return (Criteria) this;
        }

        public Criteria andListImageIsNotNull() {
            addCriterion("list_image is not null");
            return (Criteria) this;
        }

        public Criteria andListImageEqualTo(String value) {
            addCriterion("list_image =", value, "listImage");
            return (Criteria) this;
        }

        public Criteria andListImageNotEqualTo(String value) {
            addCriterion("list_image <>", value, "listImage");
            return (Criteria) this;
        }

        public Criteria andListImageGreaterThan(String value) {
            addCriterion("list_image >", value, "listImage");
            return (Criteria) this;
        }

        public Criteria andListImageGreaterThanOrEqualTo(String value) {
            addCriterion("list_image >=", value, "listImage");
            return (Criteria) this;
        }

        public Criteria andListImageLessThan(String value) {
            addCriterion("list_image <", value, "listImage");
            return (Criteria) this;
        }

        public Criteria andListImageLessThanOrEqualTo(String value) {
            addCriterion("list_image <=", value, "listImage");
            return (Criteria) this;
        }

        public Criteria andListImageLike(String value) {
            addCriterion("list_image like", value, "listImage");
            return (Criteria) this;
        }

        public Criteria andListImageNotLike(String value) {
            addCriterion("list_image not like", value, "listImage");
            return (Criteria) this;
        }

        public Criteria andListImageIn(List<String> values) {
            addCriterion("list_image in", values, "listImage");
            return (Criteria) this;
        }

        public Criteria andListImageNotIn(List<String> values) {
            addCriterion("list_image not in", values, "listImage");
            return (Criteria) this;
        }

        public Criteria andListImageBetween(String value1, String value2) {
            addCriterion("list_image between", value1, value2, "listImage");
            return (Criteria) this;
        }

        public Criteria andListImageNotBetween(String value1, String value2) {
            addCriterion("list_image not between", value1, value2, "listImage");
            return (Criteria) this;
        }

        public Criteria andBannerImageIsNull() {
            addCriterion("banner_image is null");
            return (Criteria) this;
        }

        public Criteria andBannerImageIsNotNull() {
            addCriterion("banner_image is not null");
            return (Criteria) this;
        }

        public Criteria andBannerImageEqualTo(String value) {
            addCriterion("banner_image =", value, "bannerImage");
            return (Criteria) this;
        }

        public Criteria andBannerImageNotEqualTo(String value) {
            addCriterion("banner_image <>", value, "bannerImage");
            return (Criteria) this;
        }

        public Criteria andBannerImageGreaterThan(String value) {
            addCriterion("banner_image >", value, "bannerImage");
            return (Criteria) this;
        }

        public Criteria andBannerImageGreaterThanOrEqualTo(String value) {
            addCriterion("banner_image >=", value, "bannerImage");
            return (Criteria) this;
        }

        public Criteria andBannerImageLessThan(String value) {
            addCriterion("banner_image <", value, "bannerImage");
            return (Criteria) this;
        }

        public Criteria andBannerImageLessThanOrEqualTo(String value) {
            addCriterion("banner_image <=", value, "bannerImage");
            return (Criteria) this;
        }

        public Criteria andBannerImageLike(String value) {
            addCriterion("banner_image like", value, "bannerImage");
            return (Criteria) this;
        }

        public Criteria andBannerImageNotLike(String value) {
            addCriterion("banner_image not like", value, "bannerImage");
            return (Criteria) this;
        }

        public Criteria andBannerImageIn(List<String> values) {
            addCriterion("banner_image in", values, "bannerImage");
            return (Criteria) this;
        }

        public Criteria andBannerImageNotIn(List<String> values) {
            addCriterion("banner_image not in", values, "bannerImage");
            return (Criteria) this;
        }

        public Criteria andBannerImageBetween(String value1, String value2) {
            addCriterion("banner_image between", value1, value2, "bannerImage");
            return (Criteria) this;
        }

        public Criteria andBannerImageNotBetween(String value1, String value2) {
            addCriterion("banner_image not between", value1, value2, "bannerImage");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("author like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("author not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andHotNoticeIsNull() {
            addCriterion("hot_notice is null");
            return (Criteria) this;
        }

        public Criteria andHotNoticeIsNotNull() {
            addCriterion("hot_notice is not null");
            return (Criteria) this;
        }

        public Criteria andHotNoticeEqualTo(Integer value) {
            addCriterion("hot_notice =", value, "hotNotice");
            return (Criteria) this;
        }

        public Criteria andHotNoticeNotEqualTo(Integer value) {
            addCriterion("hot_notice <>", value, "hotNotice");
            return (Criteria) this;
        }

        public Criteria andHotNoticeGreaterThan(Integer value) {
            addCriterion("hot_notice >", value, "hotNotice");
            return (Criteria) this;
        }

        public Criteria andHotNoticeGreaterThanOrEqualTo(Integer value) {
            addCriterion("hot_notice >=", value, "hotNotice");
            return (Criteria) this;
        }

        public Criteria andHotNoticeLessThan(Integer value) {
            addCriterion("hot_notice <", value, "hotNotice");
            return (Criteria) this;
        }

        public Criteria andHotNoticeLessThanOrEqualTo(Integer value) {
            addCriterion("hot_notice <=", value, "hotNotice");
            return (Criteria) this;
        }

        public Criteria andHotNoticeIn(List<Integer> values) {
            addCriterion("hot_notice in", values, "hotNotice");
            return (Criteria) this;
        }

        public Criteria andHotNoticeNotIn(List<Integer> values) {
            addCriterion("hot_notice not in", values, "hotNotice");
            return (Criteria) this;
        }

        public Criteria andHotNoticeBetween(Integer value1, Integer value2) {
            addCriterion("hot_notice between", value1, value2, "hotNotice");
            return (Criteria) this;
        }

        public Criteria andHotNoticeNotBetween(Integer value1, Integer value2) {
            addCriterion("hot_notice not between", value1, value2, "hotNotice");
            return (Criteria) this;
        }

        public Criteria andTopNoticeIsNull() {
            addCriterion("top_notice is null");
            return (Criteria) this;
        }

        public Criteria andTopNoticeIsNotNull() {
            addCriterion("top_notice is not null");
            return (Criteria) this;
        }

        public Criteria andTopNoticeEqualTo(Integer value) {
            addCriterion("top_notice =", value, "topNotice");
            return (Criteria) this;
        }

        public Criteria andTopNoticeNotEqualTo(Integer value) {
            addCriterion("top_notice <>", value, "topNotice");
            return (Criteria) this;
        }

        public Criteria andTopNoticeGreaterThan(Integer value) {
            addCriterion("top_notice >", value, "topNotice");
            return (Criteria) this;
        }

        public Criteria andTopNoticeGreaterThanOrEqualTo(Integer value) {
            addCriterion("top_notice >=", value, "topNotice");
            return (Criteria) this;
        }

        public Criteria andTopNoticeLessThan(Integer value) {
            addCriterion("top_notice <", value, "topNotice");
            return (Criteria) this;
        }

        public Criteria andTopNoticeLessThanOrEqualTo(Integer value) {
            addCriterion("top_notice <=", value, "topNotice");
            return (Criteria) this;
        }

        public Criteria andTopNoticeIn(List<Integer> values) {
            addCriterion("top_notice in", values, "topNotice");
            return (Criteria) this;
        }

        public Criteria andTopNoticeNotIn(List<Integer> values) {
            addCriterion("top_notice not in", values, "topNotice");
            return (Criteria) this;
        }

        public Criteria andTopNoticeBetween(Integer value1, Integer value2) {
            addCriterion("top_notice between", value1, value2, "topNotice");
            return (Criteria) this;
        }

        public Criteria andTopNoticeNotBetween(Integer value1, Integer value2) {
            addCriterion("top_notice not between", value1, value2, "topNotice");
            return (Criteria) this;
        }

        public Criteria andLatestNoticeIsNull() {
            addCriterion("latest_notice is null");
            return (Criteria) this;
        }

        public Criteria andLatestNoticeIsNotNull() {
            addCriterion("latest_notice is not null");
            return (Criteria) this;
        }

        public Criteria andLatestNoticeEqualTo(Integer value) {
            addCriterion("latest_notice =", value, "latestNotice");
            return (Criteria) this;
        }

        public Criteria andLatestNoticeNotEqualTo(Integer value) {
            addCriterion("latest_notice <>", value, "latestNotice");
            return (Criteria) this;
        }

        public Criteria andLatestNoticeGreaterThan(Integer value) {
            addCriterion("latest_notice >", value, "latestNotice");
            return (Criteria) this;
        }

        public Criteria andLatestNoticeGreaterThanOrEqualTo(Integer value) {
            addCriterion("latest_notice >=", value, "latestNotice");
            return (Criteria) this;
        }

        public Criteria andLatestNoticeLessThan(Integer value) {
            addCriterion("latest_notice <", value, "latestNotice");
            return (Criteria) this;
        }

        public Criteria andLatestNoticeLessThanOrEqualTo(Integer value) {
            addCriterion("latest_notice <=", value, "latestNotice");
            return (Criteria) this;
        }

        public Criteria andLatestNoticeIn(List<Integer> values) {
            addCriterion("latest_notice in", values, "latestNotice");
            return (Criteria) this;
        }

        public Criteria andLatestNoticeNotIn(List<Integer> values) {
            addCriterion("latest_notice not in", values, "latestNotice");
            return (Criteria) this;
        }

        public Criteria andLatestNoticeBetween(Integer value1, Integer value2) {
            addCriterion("latest_notice between", value1, value2, "latestNotice");
            return (Criteria) this;
        }

        public Criteria andLatestNoticeNotBetween(Integer value1, Integer value2) {
            addCriterion("latest_notice not between", value1, value2, "latestNotice");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNull() {
            addCriterion("create_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNotNull() {
            addCriterion("create_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateNameEqualTo(String value) {
            addCriterion("create_name =", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("create_name <>", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThan(String value) {
            addCriterion("create_name >", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_name >=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThan(String value) {
            addCriterion("create_name <", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("create_name <=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLike(String value) {
            addCriterion("create_name like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotLike(String value) {
            addCriterion("create_name not like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameIn(List<String> values) {
            addCriterion("create_name in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("create_name not in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("create_name between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("create_name not between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNull() {
            addCriterion("update_name is null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNotNull() {
            addCriterion("update_name is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameEqualTo(String value) {
            addCriterion("update_name =", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotEqualTo(String value) {
            addCriterion("update_name <>", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThan(String value) {
            addCriterion("update_name >", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
            addCriterion("update_name >=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThan(String value) {
            addCriterion("update_name <", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThanOrEqualTo(String value) {
            addCriterion("update_name <=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLike(String value) {
            addCriterion("update_name like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotLike(String value) {
            addCriterion("update_name not like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIn(List<String> values) {
            addCriterion("update_name in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotIn(List<String> values) {
            addCriterion("update_name not in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameBetween(String value1, String value2) {
            addCriterion("update_name between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotBetween(String value1, String value2) {
            addCriterion("update_name not between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andSysCompanyCodeIsNull() {
            addCriterion("sys_company_code is null");
            return (Criteria) this;
        }

        public Criteria andSysCompanyCodeIsNotNull() {
            addCriterion("sys_company_code is not null");
            return (Criteria) this;
        }

        public Criteria andSysCompanyCodeEqualTo(String value) {
            addCriterion("sys_company_code =", value, "sysCompanyCode");
            return (Criteria) this;
        }

        public Criteria andSysCompanyCodeNotEqualTo(String value) {
            addCriterion("sys_company_code <>", value, "sysCompanyCode");
            return (Criteria) this;
        }

        public Criteria andSysCompanyCodeGreaterThan(String value) {
            addCriterion("sys_company_code >", value, "sysCompanyCode");
            return (Criteria) this;
        }

        public Criteria andSysCompanyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("sys_company_code >=", value, "sysCompanyCode");
            return (Criteria) this;
        }

        public Criteria andSysCompanyCodeLessThan(String value) {
            addCriterion("sys_company_code <", value, "sysCompanyCode");
            return (Criteria) this;
        }

        public Criteria andSysCompanyCodeLessThanOrEqualTo(String value) {
            addCriterion("sys_company_code <=", value, "sysCompanyCode");
            return (Criteria) this;
        }

        public Criteria andSysCompanyCodeLike(String value) {
            addCriterion("sys_company_code like", value, "sysCompanyCode");
            return (Criteria) this;
        }

        public Criteria andSysCompanyCodeNotLike(String value) {
            addCriterion("sys_company_code not like", value, "sysCompanyCode");
            return (Criteria) this;
        }

        public Criteria andSysCompanyCodeIn(List<String> values) {
            addCriterion("sys_company_code in", values, "sysCompanyCode");
            return (Criteria) this;
        }

        public Criteria andSysCompanyCodeNotIn(List<String> values) {
            addCriterion("sys_company_code not in", values, "sysCompanyCode");
            return (Criteria) this;
        }

        public Criteria andSysCompanyCodeBetween(String value1, String value2) {
            addCriterion("sys_company_code between", value1, value2, "sysCompanyCode");
            return (Criteria) this;
        }

        public Criteria andSysCompanyCodeNotBetween(String value1, String value2) {
            addCriterion("sys_company_code not between", value1, value2, "sysCompanyCode");
            return (Criteria) this;
        }

        public Criteria andSysOrgCodeIsNull() {
            addCriterion("sys_org_code is null");
            return (Criteria) this;
        }

        public Criteria andSysOrgCodeIsNotNull() {
            addCriterion("sys_org_code is not null");
            return (Criteria) this;
        }

        public Criteria andSysOrgCodeEqualTo(String value) {
            addCriterion("sys_org_code =", value, "sysOrgCode");
            return (Criteria) this;
        }

        public Criteria andSysOrgCodeNotEqualTo(String value) {
            addCriterion("sys_org_code <>", value, "sysOrgCode");
            return (Criteria) this;
        }

        public Criteria andSysOrgCodeGreaterThan(String value) {
            addCriterion("sys_org_code >", value, "sysOrgCode");
            return (Criteria) this;
        }

        public Criteria andSysOrgCodeGreaterThanOrEqualTo(String value) {
            addCriterion("sys_org_code >=", value, "sysOrgCode");
            return (Criteria) this;
        }

        public Criteria andSysOrgCodeLessThan(String value) {
            addCriterion("sys_org_code <", value, "sysOrgCode");
            return (Criteria) this;
        }

        public Criteria andSysOrgCodeLessThanOrEqualTo(String value) {
            addCriterion("sys_org_code <=", value, "sysOrgCode");
            return (Criteria) this;
        }

        public Criteria andSysOrgCodeLike(String value) {
            addCriterion("sys_org_code like", value, "sysOrgCode");
            return (Criteria) this;
        }

        public Criteria andSysOrgCodeNotLike(String value) {
            addCriterion("sys_org_code not like", value, "sysOrgCode");
            return (Criteria) this;
        }

        public Criteria andSysOrgCodeIn(List<String> values) {
            addCriterion("sys_org_code in", values, "sysOrgCode");
            return (Criteria) this;
        }

        public Criteria andSysOrgCodeNotIn(List<String> values) {
            addCriterion("sys_org_code not in", values, "sysOrgCode");
            return (Criteria) this;
        }

        public Criteria andSysOrgCodeBetween(String value1, String value2) {
            addCriterion("sys_org_code between", value1, value2, "sysOrgCode");
            return (Criteria) this;
        }

        public Criteria andSysOrgCodeNotBetween(String value1, String value2) {
            addCriterion("sys_org_code not between", value1, value2, "sysOrgCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ys_notice
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 07 11:46:29 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}