package com.dce.business.entity.message;

import java.util.Date;

public class TYsNotice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.id
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.notice_type
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private Integer noticeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.title
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.list_image
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private String listImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.banner_image
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private String bannerImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.author
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.hot_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private Integer hotNotice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.top_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private Integer topNotice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.latest_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private Integer latestNotice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.remark
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.status
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.create_date
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.create_name
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.update_date
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.update_name
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.sys_company_code
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private String sysCompanyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.sys_org_code
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private String sysOrgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_notice.content
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.id
     *
     * @return the value of t_ys_notice.id
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.id
     *
     * @param id the value for t_ys_notice.id
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.notice_type
     *
     * @return the value of t_ys_notice.notice_type
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public Integer getNoticeType() {
        return noticeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.notice_type
     *
     * @param noticeType the value for t_ys_notice.notice_type
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setNoticeType(Integer noticeType) {
        this.noticeType = noticeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.title
     *
     * @return the value of t_ys_notice.title
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.title
     *
     * @param title the value for t_ys_notice.title
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.list_image
     *
     * @return the value of t_ys_notice.list_image
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public String getListImage() {
        return listImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.list_image
     *
     * @param listImage the value for t_ys_notice.list_image
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setListImage(String listImage) {
        this.listImage = listImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.banner_image
     *
     * @return the value of t_ys_notice.banner_image
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public String getBannerImage() {
        return bannerImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.banner_image
     *
     * @param bannerImage the value for t_ys_notice.banner_image
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setBannerImage(String bannerImage) {
        this.bannerImage = bannerImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.author
     *
     * @return the value of t_ys_notice.author
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.author
     *
     * @param author the value for t_ys_notice.author
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.hot_notice
     *
     * @return the value of t_ys_notice.hot_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public Integer getHotNotice() {
        return hotNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.hot_notice
     *
     * @param hotNotice the value for t_ys_notice.hot_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setHotNotice(Integer hotNotice) {
        this.hotNotice = hotNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.top_notice
     *
     * @return the value of t_ys_notice.top_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public Integer getTopNotice() {
        return topNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.top_notice
     *
     * @param topNotice the value for t_ys_notice.top_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setTopNotice(Integer topNotice) {
        this.topNotice = topNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.latest_notice
     *
     * @return the value of t_ys_notice.latest_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public Integer getLatestNotice() {
        return latestNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.latest_notice
     *
     * @param latestNotice the value for t_ys_notice.latest_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setLatestNotice(Integer latestNotice) {
        this.latestNotice = latestNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.remark
     *
     * @return the value of t_ys_notice.remark
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.remark
     *
     * @param remark the value for t_ys_notice.remark
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.status
     *
     * @return the value of t_ys_notice.status
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.status
     *
     * @param status the value for t_ys_notice.status
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.create_date
     *
     * @return the value of t_ys_notice.create_date
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.create_date
     *
     * @param createDate the value for t_ys_notice.create_date
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.create_name
     *
     * @return the value of t_ys_notice.create_name
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.create_name
     *
     * @param createName the value for t_ys_notice.create_name
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setCreateName(String createName) {
        this.createName = createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.update_date
     *
     * @return the value of t_ys_notice.update_date
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.update_date
     *
     * @param updateDate the value for t_ys_notice.update_date
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.update_name
     *
     * @return the value of t_ys_notice.update_name
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.update_name
     *
     * @param updateName the value for t_ys_notice.update_name
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.sys_company_code
     *
     * @return the value of t_ys_notice.sys_company_code
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public String getSysCompanyCode() {
        return sysCompanyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.sys_company_code
     *
     * @param sysCompanyCode the value for t_ys_notice.sys_company_code
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setSysCompanyCode(String sysCompanyCode) {
        this.sysCompanyCode = sysCompanyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.sys_org_code
     *
     * @return the value of t_ys_notice.sys_org_code
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public String getSysOrgCode() {
        return sysOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.sys_org_code
     *
     * @param sysOrgCode the value for t_ys_notice.sys_org_code
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setSysOrgCode(String sysOrgCode) {
        this.sysOrgCode = sysOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_notice.content
     *
     * @return the value of t_ys_notice.content
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_notice.content
     *
     * @param content the value for t_ys_notice.content
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}