package com.dce.business.entity.user;

public class UserPromoteDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_user_promote.promote_id
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    private Integer promoteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_user_promote.user_level
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    private Integer userLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_user_promote.promote_level
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    private Integer promoteLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_user_promote.min_qty
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    private Integer minQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_user_promote.max_qty
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    private Integer maxQty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_user_promote.promote_id
     *
     * @return the value of ct_user_promote.promote_id
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    public Integer getPromoteId() {
        return promoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_user_promote.promote_id
     *
     * @param promoteId the value for ct_user_promote.promote_id
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    public void setPromoteId(Integer promoteId) {
        this.promoteId = promoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_user_promote.user_level
     *
     * @return the value of ct_user_promote.user_level
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    public Integer getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_user_promote.user_level
     *
     * @param userLevel the value for ct_user_promote.user_level
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_user_promote.promote_level
     *
     * @return the value of ct_user_promote.promote_level
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    public Integer getPromoteLevel() {
        return promoteLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_user_promote.promote_level
     *
     * @param promoteLevel the value for ct_user_promote.promote_level
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    public void setPromoteLevel(Integer promoteLevel) {
        this.promoteLevel = promoteLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_user_promote.min_qty
     *
     * @return the value of ct_user_promote.min_qty
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    public Integer getMinQty() {
        return minQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_user_promote.min_qty
     *
     * @param minQty the value for ct_user_promote.min_qty
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    public void setMinQty(Integer minQty) {
        this.minQty = minQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_user_promote.max_qty
     *
     * @return the value of ct_user_promote.max_qty
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    public Integer getMaxQty() {
        return maxQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_user_promote.max_qty
     *
     * @param maxQty the value for ct_user_promote.max_qty
     *
     * @mbg.generated Wed Aug 22 16:20:11 CST 2018
     */
    public void setMaxQty(Integer maxQty) {
        this.maxQty = maxQty;
    }
}