package com.dce.business.dao.message;

import com.dce.business.entity.message.Notice;
import com.dce.business.entity.message.NoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TYsNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    long countByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int deleteByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int insertSelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    List<Notice> selectByExampleWithBLOBs(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    List<Notice> selectByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    Notice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") Notice record, @Param("example") NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Notice record, @Param("example") NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int updateByExample(@Param("record") Notice record, @Param("example") NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int updateByPrimaryKeySelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int updateByPrimaryKey(Notice record);
}