package com.dce.business.dao.message;

import com.dce.business.entity.message.TYsNotice;
import com.dce.business.entity.message.TYsNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TYsNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    long countByExample(TYsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int deleteByExample(TYsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int insert(TYsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int insertSelective(TYsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    List<TYsNotice> selectByExampleWithBLOBs(TYsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    List<TYsNotice> selectByExample(TYsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    TYsNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") TYsNotice record, @Param("example") TYsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") TYsNotice record, @Param("example") TYsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int updateByExample(@Param("record") TYsNotice record, @Param("example") TYsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int updateByPrimaryKeySelective(TYsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(TYsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ys_notice
     *
     * @mbg.generated Tue Aug 07 11:46:29 CST 2018
     */
    int updateByPrimaryKey(TYsNotice record);
}