package com.dce.business.dao.travel;

import com.dce.business.entity.travel.applyTravel;
import com.dce.business.entity.travel.applyTravelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface applyTravelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    long countByExample(applyTravelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int deleteByExample(applyTravelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int insert(applyTravel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int insertSelective(applyTravel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    List<applyTravel> selectByExample(applyTravelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") applyTravel record, @Param("example") applyTravelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_apply_travel
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int updateByExample(@Param("record") applyTravel record, @Param("example") applyTravelExample example);
}