package com.dce.business.dao.travel;

import com.dce.business.entity.travel.travelPath;
import com.dce.business.entity.travel.travelPathExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface travelPathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    long countByExample(travelPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int deleteByExample(travelPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int deleteByPrimaryKey(Integer pathid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int insert(travelPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int insertSelective(travelPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    List<travelPath> selectByExample(travelPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    travelPath selectByPrimaryKey(Integer pathid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") travelPath record, @Param("example") travelPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int updateByExample(@Param("record") travelPath record, @Param("example") travelPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int updateByPrimaryKeySelective(travelPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_travel_path
     *
     * @mbg.generated Tue Aug 07 14:21:23 CST 2018
     */
    int updateByPrimaryKey(travelPath record);
}