package com.dce.business.entity.order;

import java.math.BigDecimal;
import java.util.Date;

public class Order {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.orderId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Long orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.orderCode
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private String ordercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.userId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.qty
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private BigDecimal qty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.totalPrice
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private BigDecimal totalprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.recAddress
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private String recaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.createTime
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.orderStatus
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Integer orderstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.payStatus
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Integer paystatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.payTime
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Date paytime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.orderType
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Integer ordertype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.matchOrderId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Long matchorderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.salqty
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private BigDecimal salqty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.accountType
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private String accounttype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.goodsId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Long goodsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.price
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Long price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.addressId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Integer addressid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.remark
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.orderId
	 * @return  the value of ct_order.orderId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Long getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.orderId
	 * @param orderid  the value for ct_order.orderId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setOrderid(Long orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.orderCode
	 * @return  the value of ct_order.orderCode
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public String getOrdercode() {
		return ordercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.orderCode
	 * @param ordercode  the value for ct_order.orderCode
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setOrdercode(String ordercode) {
		this.ordercode = ordercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.userId
	 * @return  the value of ct_order.userId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.userId
	 * @param userid  the value for ct_order.userId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.qty
	 * @return  the value of ct_order.qty
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public BigDecimal getQty() {
		return qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.qty
	 * @param qty  the value for ct_order.qty
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.totalPrice
	 * @return  the value of ct_order.totalPrice
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public BigDecimal getTotalprice() {
		return totalprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.totalPrice
	 * @param totalprice  the value for ct_order.totalPrice
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setTotalprice(BigDecimal totalprice) {
		this.totalprice = totalprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.recAddress
	 * @return  the value of ct_order.recAddress
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public String getRecaddress() {
		return recaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.recAddress
	 * @param recaddress  the value for ct_order.recAddress
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setRecaddress(String recaddress) {
		this.recaddress = recaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.createTime
	 * @return  the value of ct_order.createTime
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.createTime
	 * @param createtime  the value for ct_order.createTime
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.orderStatus
	 * @return  the value of ct_order.orderStatus
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Integer getOrderstatus() {
		return orderstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.orderStatus
	 * @param orderstatus  the value for ct_order.orderStatus
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setOrderstatus(Integer orderstatus) {
		this.orderstatus = orderstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.payStatus
	 * @return  the value of ct_order.payStatus
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Integer getPaystatus() {
		return paystatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.payStatus
	 * @param paystatus  the value for ct_order.payStatus
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setPaystatus(Integer paystatus) {
		this.paystatus = paystatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.payTime
	 * @return  the value of ct_order.payTime
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Date getPaytime() {
		return paytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.payTime
	 * @param paytime  the value for ct_order.payTime
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setPaytime(Date paytime) {
		this.paytime = paytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.orderType
	 * @return  the value of ct_order.orderType
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Integer getOrdertype() {
		return ordertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.orderType
	 * @param ordertype  the value for ct_order.orderType
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setOrdertype(Integer ordertype) {
		this.ordertype = ordertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.matchOrderId
	 * @return  the value of ct_order.matchOrderId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Long getMatchorderid() {
		return matchorderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.matchOrderId
	 * @param matchorderid  the value for ct_order.matchOrderId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setMatchorderid(Long matchorderid) {
		this.matchorderid = matchorderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.salqty
	 * @return  the value of ct_order.salqty
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public BigDecimal getSalqty() {
		return salqty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.salqty
	 * @param salqty  the value for ct_order.salqty
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setSalqty(BigDecimal salqty) {
		this.salqty = salqty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.accountType
	 * @return  the value of ct_order.accountType
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public String getAccounttype() {
		return accounttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.accountType
	 * @param accounttype  the value for ct_order.accountType
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setAccounttype(String accounttype) {
		this.accounttype = accounttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.goodsId
	 * @return  the value of ct_order.goodsId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Long getGoodsid() {
		return goodsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.goodsId
	 * @param goodsid  the value for ct_order.goodsId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setGoodsid(Long goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.price
	 * @return  the value of ct_order.price
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Long getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.price
	 * @param price  the value for ct_order.price
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setPrice(Long price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.addressId
	 * @return  the value of ct_order.addressId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Integer getAddressid() {
		return addressid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.addressId
	 * @param addressid  the value for ct_order.addressId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setAddressid(Integer addressid) {
		this.addressid = addressid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.remark
	 * @return  the value of ct_order.remark
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.remark
	 * @param remark  the value for ct_order.remark
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}