package com.dce.business.entity.order;

public class OrderDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_orderdetail.orderDetailId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Integer orderdetailid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_orderdetail.orderId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Integer orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_orderdetail.goodsId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Integer goodsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_orderdetail.quantity
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_orderdetail.price
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_orderdetail.remark
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_orderdetail.orderDetailId
	 * @return  the value of ct_orderdetail.orderDetailId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Integer getOrderdetailid() {
		return orderdetailid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_orderdetail.orderDetailId
	 * @param orderdetailid  the value for ct_orderdetail.orderDetailId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setOrderdetailid(Integer orderdetailid) {
		this.orderdetailid = orderdetailid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_orderdetail.orderId
	 * @return  the value of ct_orderdetail.orderId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Integer getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_orderdetail.orderId
	 * @param orderid  the value for ct_orderdetail.orderId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_orderdetail.goodsId
	 * @return  the value of ct_orderdetail.goodsId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Integer getGoodsid() {
		return goodsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_orderdetail.goodsId
	 * @param goodsid  the value for ct_orderdetail.goodsId
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_orderdetail.quantity
	 * @return  the value of ct_orderdetail.quantity
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_orderdetail.quantity
	 * @param quantity  the value for ct_orderdetail.quantity
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_orderdetail.price
	 * @return  the value of ct_orderdetail.price
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_orderdetail.price
	 * @param price  the value for ct_orderdetail.price
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_orderdetail.remark
	 * @return  the value of ct_orderdetail.remark
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_orderdetail.remark
	 * @param remark  the value for ct_orderdetail.remark
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}