package com.dce.business.dao.order;

import com.dce.business.entity.order.Order;
import com.dce.business.entity.order.OrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	long countByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int deleteByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int deleteByPrimaryKey(Long orderid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int insert(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int insertSelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	List<Order> selectByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	Order selectByPrimaryKey(Long orderid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int updateByPrimaryKeySelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int updateByPrimaryKey(Order record);
}