package com.dce.business.dao.order;

import com.dce.business.entity.order.OrderDetail;
import com.dce.business.entity.order.OrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_orderdetail
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	long countByExample(OrderDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_orderdetail
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int deleteByExample(OrderDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_orderdetail
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int deleteByPrimaryKey(Integer orderdetailid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_orderdetail
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int insert(OrderDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_orderdetail
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int insertSelective(OrderDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_orderdetail
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	List<OrderDetail> selectByExample(OrderDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_orderdetail
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	OrderDetail selectByPrimaryKey(Integer orderdetailid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_orderdetail
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int updateByExampleSelective(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_orderdetail
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int updateByExample(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_orderdetail
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int updateByPrimaryKeySelective(OrderDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_orderdetail
	 * @mbg.generated  Tue Aug 07 12:18:12 CST 2018
	 */
	int updateByPrimaryKey(OrderDetail record);
}