package com.dce.business.dao.feedback;

import com.dce.business.entity.feedback.FeedBack;
import com.dce.business.entity.feedback.FeedBackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeedBackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_feedback
     *
     * @mbg.generated Tue Aug 07 14:20:15 CST 2018
     */
    long countByExample(FeedBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_feedback
     *
     * @mbg.generated Tue Aug 07 14:20:15 CST 2018
     */
    int deleteByExample(FeedBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_feedback
     *
     * @mbg.generated Tue Aug 07 14:20:15 CST 2018
     */
    int deleteByPrimaryKey(Integer feedbackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_feedback
     *
     * @mbg.generated Tue Aug 07 14:20:15 CST 2018
     */
    int insert(FeedBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_feedback
     *
     * @mbg.generated Tue Aug 07 14:20:15 CST 2018
     */
    int insertSelective(FeedBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_feedback
     *
     * @mbg.generated Tue Aug 07 14:20:15 CST 2018
     */
    List<FeedBack> selectByExample(FeedBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_feedback
     *
     * @mbg.generated Tue Aug 07 14:20:15 CST 2018
     */
    FeedBack selectByPrimaryKey(Integer feedbackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_feedback
     *
     * @mbg.generated Tue Aug 07 14:20:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") FeedBack record, @Param("example") FeedBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_feedback
     *
     * @mbg.generated Tue Aug 07 14:20:15 CST 2018
     */
    int updateByExample(@Param("record") FeedBack record, @Param("example") FeedBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_feedback
     *
     * @mbg.generated Tue Aug 07 14:20:15 CST 2018
     */
    int updateByPrimaryKeySelective(FeedBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_user_feedback
     *
     * @mbg.generated Tue Aug 07 14:20:15 CST 2018
     */
    int updateByPrimaryKey(FeedBack record);
}